pipeline:
  agent:
    label: any

  stages:
    - name: 'Checkout'
      steps:
        - checkout:
            scm:
              git:
                url: 'https://github.com/amansikarwar1988/test2'
                branch: 'main'

    - name: 'List Directory'
      steps:
        - bat: 'dir'  # Run the 'dir' command and capture its output
          id: listDirectory  # Optional: Step ID for reference

    - name: 'Build'
      steps:
        - bat: 'mvn -B package'  # Build the project using Maven

    - name: 'Test'
      steps:
        - bat: 'mvn test'  # Run tests using Maven

    - name: 'Run'
      steps:
        - script:
            script: |
              start /B cmd /c "mvn spring-boot:run"
              echo "Waiting for Spring Boot application to start..."
              timeout /t 30 > nul
              :: Check if the application is running
              curl -s -o NUL -w "%{http_code}" http://localhost:8080/

  post:
    success:
      script:
        script: |
          echo 'Pipeline succeeded!'
    failure:
      script:
        script: |
          echo 'Pipeline failed!'
